### ISSUE TITLE
Website bug wrong project list 

### ISSUE THREAD

**Issue by ayoola00** [hartloff/Education#9]
The website gets data from last semester when you clicked on the list of project, I manual change the URL before spring 18  projects are shown.

REPRODUCE
log into the course website
click on the project list (side bar)
and you'll be shown fall 17 lists of projects

**Comment by hartloff** [comment]
Can you be more specific. How do you get to the course website before logging on? There are 4 offerings of CSE442 currently hosted on the site that can found here (https://fury.cse.buffalo.edu/courses/) and want to keep the other 3 live so anyone can still see the previous projects.

**Comment by ayoola00** [comment]
when logged into the default website, it brings up the old semester projects as default

**Comment by hartloff** [comment]
Can you define the default website? Providing the link you use to access the site would help me track this down. The expected behavior after logging in is the site sends you to your last active page. If your default page is the old 442 then it will send you back to that page. Is your default page the current 442 and it's sending to the old 442 after logging in?

**Comment by jessehartloff** [comment]
Cannot duplicate
